; Inno Setup script for PDF Cropper.
; Compiled by CI with:  ISCC.exe /DAppVersion=X.Y.Z installer\pdf-cropper.iss
; Expects the PyInstaller output in dist\pdf-cropper (repo root).
;
; The registry layout below mirrors win_register() in pdf_cropper.py
; (verb PDFCropper.crop): keep them in sync.
; Every user-visible string lives in [CustomMessages], once per language.

#ifndef AppVersion
  #define AppVersion "dev"
#endif

[Setup]
AppId={{3961D302-A649-4493-80D1-443A426B3589}
AppName=PDF Cropper
AppVersion={#AppVersion}
AppPublisher=Daniel Grasso
AppPublisherURL=https://github.com/daniel-g-carrasco/pdf-cropper
AppSupportURL=https://github.com/daniel-g-carrasco/pdf-cropper/issues
AppUpdatesURL=https://github.com/daniel-g-carrasco/pdf-cropper/releases
DefaultDirName={autopf}\PDF Cropper
DefaultGroupName=PDF Cropper
DisableProgramGroupPage=yes
; per-user install by default (no UAC); the dialog (or /ALLUSERS, /CURRENTUSER
; on the command line) lets the user choose
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog commandline
OutputBaseFilename=pdf-cropper-setup-v{#AppVersion}-windows-x64
SetupIconFile=..\assets\icon.ico
UninstallDisplayIcon={app}\pdf-cropper.exe
; app icon in the wizard, one bitmap per DPI scale (generated by tools/make_icon.py)
WizardSmallImageFile=wizard-small-*.bmp
WizardImageFile=wizard-large-*.bmp
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
ChangesAssociations=yes
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
; upgrades: close the running app instead of failing on files in use
CloseApplications=yes
RestartApplications=no

[Languages]
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[CustomMessages]
italian.TaskContextMenu=Aggiungi «Ritaglia i bordi bianchi con PDF Cropper» al menu contestuale dei file PDF
english.TaskContextMenu=Add "Crop white margins with PDF Cropper" to the context menu of PDF files
italian.VerbCrop=Ritaglia i bordi bianchi con PDF Cropper
english.VerbCrop=Crop white margins with PDF Cropper

[Tasks]
Name: "contextmenu"; Description: "{cm:TaskContextMenu}"
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; Flags: unchecked

[Files]
Source: "..\dist\pdf-cropper\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion

[Icons]
Name: "{group}\PDF Cropper"; Filename: "{app}\pdf-cropper.exe"
Name: "{autodesktop}\PDF Cropper"; Filename: "{app}\pdf-cropper.exe"; Tasks: desktopicon

[Registry]
; --- context-menu verb on every PDF, whatever the default app is (task).
;     Nothing else is registered: this tool is not a PDF viewer and must not
;     compete for the .pdf association.
;     MultiSelectModel=Player: Explorer runs it for each selected file with
;     no "too many files" prompt; the app merges them into its single window.
Root: HKA; Subkey: "Software\Classes\SystemFileAssociations\.pdf\shell\PDFCropper.crop"; ValueType: string; ValueName: ""; ValueData: "{cm:VerbCrop}"; Flags: uninsdeletekey; Tasks: contextmenu
Root: HKA; Subkey: "Software\Classes\SystemFileAssociations\.pdf\shell\PDFCropper.crop"; ValueType: string; ValueName: "Icon"; ValueData: "{app}\pdf-cropper.exe,0"; Tasks: contextmenu
Root: HKA; Subkey: "Software\Classes\SystemFileAssociations\.pdf\shell\PDFCropper.crop"; ValueType: string; ValueName: "MultiSelectModel"; ValueData: "Player"; Tasks: contextmenu
Root: HKA; Subkey: "Software\Classes\SystemFileAssociations\.pdf\shell\PDFCropper.crop\command"; ValueType: string; ValueName: ""; ValueData: """{app}\pdf-cropper.exe"" --gui ""%1"""; Tasks: contextmenu

[INI]
; the language chosen for Setup becomes the app language. {localappdata} is
; the profile of the user running Setup (with UAC approval that is still the
; same user; only elevation with another administrator's account would land
; the setting in that other profile, which is harmless).
Filename: "{localappdata}\pdf-cropper\settings.ini"; Section: "general"; Key: "language"; String: "{code:AppLanguage}"

[UninstallDelete]
Type: filesandordirs; Name: "{localappdata}\pdf-cropper"

[UninstallRun]
; the app may have added its context-menu entry per-user from its Preferences: clean that up too
Filename: "{app}\pdf-cropper.exe"; Parameters: "--unregister"; RunOnceId: "UnregisterShell"; Flags: runhidden

[Run]
Filename: "{app}\pdf-cropper.exe"; Description: "{cm:LaunchProgram,PDF Cropper}"; Flags: nowait postinstall skipifsilent

[Code]
function AppLanguage(Param: String): String;
begin
  if ActiveLanguage = 'italian' then
    Result := 'it'
  else
    Result := 'en';
end;
